
package com.mg.menu;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MenuWsdlProject", targetNamespace = "http://menu.mg.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MenuWsdlProject {


    /**
     * 
     * @return
     *     returns java.util.List<com.mg.menu.Menu>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMenu", targetNamespace = "http://menu.mg.com/", className = "com.mg.menu.GetMenu")
    @ResponseWrapper(localName = "getMenuResponse", targetNamespace = "http://menu.mg.com/", className = "com.mg.menu.GetMenuResponse")
    @Action(input = "http://menu.mg.com/MenuWsdlProject/getMenuRequest", output = "http://menu.mg.com/MenuWsdlProject/getMenuResponse")
    public List<Menu> getMenu();

}
