
package com.mg.menu;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MenuWsdlService", targetNamespace = "http://menu.mg.com/", wsdlLocation = "http://user-pc:8080/EonCafe/MenuWsdlService?wsdl")
public class MenuWsdlService
    extends Service
{

    private final static URL MENUWSDLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MENUWSDLSERVICE_EXCEPTION;
    private final static QName MENUWSDLSERVICE_QNAME = new QName("http://menu.mg.com/", "MenuWsdlService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://user-pc:8080/EonCafe/MenuWsdlService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MENUWSDLSERVICE_WSDL_LOCATION = url;
        MENUWSDLSERVICE_EXCEPTION = e;
    }

    public MenuWsdlService() {
        super(__getWsdlLocation(), MENUWSDLSERVICE_QNAME);
    }

    public MenuWsdlService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MENUWSDLSERVICE_QNAME, features);
    }

    public MenuWsdlService(URL wsdlLocation) {
        super(wsdlLocation, MENUWSDLSERVICE_QNAME);
    }

    public MenuWsdlService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MENUWSDLSERVICE_QNAME, features);
    }

    public MenuWsdlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MenuWsdlService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MenuWsdlProject
     */
    @WebEndpoint(name = "MenuWsdlProjectPort")
    public MenuWsdlProject getMenuWsdlProjectPort() {
        return super.getPort(new QName("http://menu.mg.com/", "MenuWsdlProjectPort"), MenuWsdlProject.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MenuWsdlProject
     */
    @WebEndpoint(name = "MenuWsdlProjectPort")
    public MenuWsdlProject getMenuWsdlProjectPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://menu.mg.com/", "MenuWsdlProjectPort"), MenuWsdlProject.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MENUWSDLSERVICE_EXCEPTION!= null) {
            throw MENUWSDLSERVICE_EXCEPTION;
        }
        return MENUWSDLSERVICE_WSDL_LOCATION;
    }

}
