
package com.ws.mail;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MailWsdl", targetNamespace = "http://mail.ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MailWsdl {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMail", targetNamespace = "http://mail.ws.com/", className = "com.ws.mail.SendMail")
    @ResponseWrapper(localName = "sendMailResponse", targetNamespace = "http://mail.ws.com/", className = "com.ws.mail.SendMailResponse")
    @Action(input = "http://mail.ws.com/MailWsdl/sendMailRequest", output = "http://mail.ws.com/MailWsdl/sendMailResponse")
    public boolean sendMail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

}
