
package com.ws.mail;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MailSoapWsdlService", targetNamespace = "http://mail.ws.com/", wsdlLocation = "http://user-pc:8080/EonCafe/MailSoapWsdlService?wsdl")
public class MailSoapWsdlService
    extends Service
{

    private final static URL MAILSOAPWSDLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAILSOAPWSDLSERVICE_EXCEPTION;
    private final static QName MAILSOAPWSDLSERVICE_QNAME = new QName("http://mail.ws.com/", "MailSoapWsdlService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://user-pc:8080/EonCafe/MailSoapWsdlService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAILSOAPWSDLSERVICE_WSDL_LOCATION = url;
        MAILSOAPWSDLSERVICE_EXCEPTION = e;
    }

    public MailSoapWsdlService() {
        super(__getWsdlLocation(), MAILSOAPWSDLSERVICE_QNAME);
    }

    public MailSoapWsdlService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAILSOAPWSDLSERVICE_QNAME, features);
    }

    public MailSoapWsdlService(URL wsdlLocation) {
        super(wsdlLocation, MAILSOAPWSDLSERVICE_QNAME);
    }

    public MailSoapWsdlService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAILSOAPWSDLSERVICE_QNAME, features);
    }

    public MailSoapWsdlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MailSoapWsdlService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MailWsdl
     */
    @WebEndpoint(name = "MailWsdlPort")
    public MailWsdl getMailWsdlPort() {
        return super.getPort(new QName("http://mail.ws.com/", "MailWsdlPort"), MailWsdl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MailWsdl
     */
    @WebEndpoint(name = "MailWsdlPort")
    public MailWsdl getMailWsdlPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mail.ws.com/", "MailWsdlPort"), MailWsdl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAILSOAPWSDLSERVICE_EXCEPTION!= null) {
            throw MAILSOAPWSDLSERVICE_EXCEPTION;
        }
        return MAILSOAPWSDLSERVICE_WSDL_LOCATION;
    }

}
